import type { Patient, TaskItem } from "./types";

// 运动康复相关示例患者
export const patients: Patient[] = [
  // 门诊待入院 / 门诊康复
  {
    id: "p1",
    outpatientId: "MZ-20240412-001",
    name: "张建国",
    age: 32,
    gender: "男",
    phone: "138****2341",
    diagnosis: "右膝 ACL 断裂（运动损伤）",
    surgeryName: "右膝 ACL 重建术",
    side: "右",
    director: "王主任",
    scheduledAdmission: "2024-04-22",
    status: "outpatient-pending",
    department: "outpatient",
    urgent: true,
    notes: "篮球扭伤，需尽快重建",
  },
  {
    id: "p2",
    outpatientId: "MZ-20240412-002",
    name: "李秀兰",
    age: 28,
    gender: "女",
    phone: "139****5621",
    diagnosis: "左膝半月板撕裂（跑步损伤）",
    surgeryName: "左膝半月板缝合术",
    side: "左",
    director: "秦主任",
    scheduledAdmission: "2024-04-23",
    status: "outpatient-pending",
    department: "outpatient",
  },
  {
    id: "p3",
    outpatientId: "MZ-20240413-003",
    name: "陈志强",
    age: 35,
    gender: "男",
    phone: "137****8812",
    diagnosis: "右肩袖损伤（羽毛球）",
    surgeryName: "右肩关节镜肩袖修补",
    side: "右",
    director: "王主任",
    scheduledAdmission: "2024-04-24",
    status: "outpatient-pending",
    department: "outpatient",
  },
  {
    id: "p4",
    outpatientId: "MZ-20240413-004",
    name: "周梅芳",
    age: 26,
    gender: "女",
    phone: "135****2245",
    diagnosis: "右踝跟腱断裂（瑜伽）",
    surgeryName: "右跟腱缝合术",
    side: "右",
    director: "秦主任",
    scheduledAdmission: "2024-04-25",
    status: "outpatient-pending",
    department: "outpatient",
  },
  // 门诊康复（无需手术 / 术后回门诊康复）
  {
    id: "po1",
    outpatientId: "MZ-20240410-051",
    name: "韩启航",
    age: 24,
    gender: "男",
    phone: "138****9921",
    diagnosis: "髌骨关节疼痛综合征",
    director: "秦主任",
    responsibleTherapist: "朱年鑫",
    status: "rehab",
    department: "outpatient",
    visitType: "first",
    notes: "门诊康复 · 每周 2 次",
  },
  {
    id: "po2",
    outpatientId: "MZ-20240407-042",
    name: "王晓彤",
    age: 30,
    gender: "女",
    phone: "139****7762",
    diagnosis: "右肩冲击综合征",
    director: "王主任",
    responsibleTherapist: "朱年鑫",
    status: "rehab",
    department: "outpatient",
    visitType: "revisit",
    notes: "门诊康复 · 力量训练阶段",
  },

  // 住院 - 待手术
  {
    id: "p5",
    outpatientId: "MZ-20240408-018",
    name: "刘德海",
    age: 29,
    gender: "男",
    phone: "138****6671",
    diagnosis: "左膝 ACL+MCL 复合损伤（足球）",
    surgeryName: "左膝 ACL 重建 + MCL 修补",
    side: "左",
    director: "王主任",
    responsibleDoctor: "朱医生",
    bedNo: "01",
    admissionDate: "2024-04-20",
    surgeryDate: "2024-04-23",
    status: "admitted",
    department: "inpatient",
    isNew: true,
    preOpAbnormal: true,
    preOpFindings: [
      { label: "Lachman 试验", value: "3+ 阳性", abnormal: true },
      { label: "MRI", value: "ACL 完全断裂", abnormal: true },
      { label: "膝关节肿胀", value: "中度", abnormal: true },
      { label: "屈膝活动度", value: "0-95°", abnormal: false },
    ],
    preOpSymptoms: {
      painVAS: 6,
      swelling: "中",
      rom: "0-95°",
      strength: "股四头肌 4 级",
      dailyFunction: "需扶拐行走，无法上下楼梯",
    },
  },
  {
    id: "p6",
    outpatientId: "MZ-20240409-022",
    name: "吴翠花",
    age: 33,
    gender: "女",
    phone: "139****1182",
    diagnosis: "右膝半月板桶柄状撕裂",
    surgeryName: "右膝半月板部分切除 + 缝合",
    side: "右",
    director: "秦主任",
    responsibleDoctor: "许医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "02",
    admissionDate: "2024-04-19",
    surgeryDate: "2024-04-23",
    status: "admitted",
    department: "inpatient",
    isNew: false,
    preOpAbnormal: false,
    preOpFindings: [
      { label: "McMurray 试验", value: "阳性", abnormal: true },
      { label: "MRI", value: "外侧半月板桶柄撕裂", abnormal: true },
      { label: "屈膝交锁", value: "无", abnormal: false },
    ],
    preOpSymptoms: {
      painVAS: 4,
      swelling: "轻",
      rom: "0-110°",
      strength: "股四头肌 4+ 级",
      dailyFunction: "可缓慢平地行走，蹲起受限",
    },
  },
  // 今日手术
  {
    id: "p7",
    outpatientId: "MZ-20240405-011",
    name: "孙顺英",
    age: 27,
    gender: "女",
    phone: "137****3398",
    diagnosis: "右肩盂唇 SLAP 损伤（游泳）",
    surgeryName: "右肩关节镜 SLAP 修补",
    side: "右",
    director: "王主任",
    responsibleDoctor: "朱医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "03",
    admissionDate: "2024-04-18",
    surgeryDate: "2024-04-22",
    status: "in-surgery",
    department: "inpatient",
  },
  // 术后
  {
    id: "p8",
    outpatientId: "MZ-20240402-008",
    name: "杨成轩",
    age: 31,
    gender: "男",
    phone: "138****4421",
    diagnosis: "左踝跟腱断裂（篮球）",
    surgeryName: "左跟腱缝合术",
    side: "左",
    director: "王主任",
    responsibleDoctor: "许医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "05",
    admissionDate: "2024-04-15",
    surgeryDate: "2024-04-19",
    status: "post-op",
    department: "inpatient",
  },
  {
    id: "p9",
    outpatientId: "MZ-20240331-002",
    name: "胡国玉",
    age: 25,
    gender: "女",
    phone: "139****7821",
    diagnosis: "右膝 PCL 损伤（滑雪）",
    surgeryName: "右膝 PCL 重建",
    side: "右",
    director: "秦主任",
    responsibleDoctor: "朱医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "08",
    admissionDate: "2024-04-13",
    surgeryDate: "2024-04-15",
    status: "rehab",
    department: "inpatient",
  },
  // 已出院 / 随访
  {
    id: "p10",
    outpatientId: "MZ-20240315-021",
    name: "何宗兰",
    age: 34,
    gender: "女",
    phone: "138****5512",
    diagnosis: "左肩袖部分撕裂",
    surgeryName: "左肩关节镜肩袖修补",
    side: "左",
    director: "王主任",
    responsibleTherapist: "朱年鑫",
    admissionDate: "2024-04-15",
    surgeryDate: "2024-04-17",
    dischargeDate: "2024-04-22",
    status: "follow-up",
    department: "inpatient",
    followUpStatus: "done",
    followUpResult: "肩外展 90°，恢复良好",
  },
  {
    id: "p11",
    outpatientId: "MZ-20240316-024",
    name: "范芳进",
    age: 22,
    gender: "女",
    phone: "139****8814",
    diagnosis: "右髌骨脱位（舞蹈）",
    surgeryName: "右髌骨内侧支持带修补",
    side: "右",
    director: "秦主任",
    responsibleTherapist: "朱年鑫",
    admissionDate: "2024-04-19",
    surgeryDate: "2024-04-21",
    dischargeDate: "2024-04-23",
    status: "follow-up",
    department: "inpatient",
    followUpStatus: "needs-second",
    followUpResult: "屈膝受限，需加强康复",
  },
];

export const todayTasks: Record<string, TaskItem[]> = {
  secretary: [
    { id: "t1", title: "门诊待入院患者电话确认", patientName: "张建国", priority: "high", type: "call", due: "今日 10:00" },
    { id: "t2", title: "门诊待入院患者电话确认", patientName: "李秀兰", priority: "high", type: "call", due: "今日 11:00" },
    { id: "t3", title: "入院前康复宣教推送", patientName: "陈志强", priority: "medium", type: "education", due: "今日 14:00" },
    { id: "t4", title: "新入院患者床旁宣教", patientName: "刘德海", bedNo: "01", priority: "medium", type: "admission" },
    { id: "t5", title: "08:00 护理交班记录", priority: "high", type: "handover", due: "今日 08:00" },
    { id: "t6", title: "DVT/血栓监测指标录入", patientName: "杨成轩", bedNo: "05", priority: "medium", type: "nursing" },
  ],
  "doctor-on-duty": [
    { id: "d1", title: "录入术前康复评估量表", patientName: "刘德海", bedNo: "01", priority: "high", type: "ocr", due: "今日 16:00" },
    { id: "d2", title: "录入术前康复评估量表", patientName: "吴翠花", bedNo: "02", priority: "high", type: "ocr", due: "今日 16:00" },
  ],
  "surgical-team": [
    { id: "s1", title: "明日手术患者确认", patientName: "刘德海", bedNo: "01", priority: "high", type: "decision" },
    { id: "s2", title: "明日手术患者确认", patientName: "吴翠花", bedNo: "02", priority: "high", type: "decision" },
    { id: "s3", title: "术中量表填写", patientName: "孙顺英", bedNo: "03", priority: "high", type: "intra-op", due: "术后即时" },
  ],
  therapist: [
    { id: "th1", title: "AI 康复方案确认", patientName: "孙顺英", bedNo: "03", priority: "high", type: "plan" },
    { id: "th4", title: "康复出院评估咨询", patientName: "胡国玉", bedNo: "08", priority: "medium", type: "discharge" },
  ],
};

export const roleMeta = {
  secretary: {
    title: "护士 / 科室秘书",
    subtitle: "Nurse & Secretary",
    description: "负责门诊待入院电话沟通、宣教推送、入院办理及住院护理交班。",
    accent: "from-sky-500 to-blue-600",
  },
  "doctor-on-duty": {
    title: "值班医生",
    subtitle: "Doctor on Duty",
    description: "汇总术前康复评估量表，OCR 录入并推送医疗团队，标记异常指标。",
    accent: "from-cyan-500 to-teal-600",
  },
  "surgical-team": {
    title: "手术医疗团队",
    subtitle: "Surgical Team",
    description: "审核术前结果决定手术与否,填写术中量表，向治疗师交接。",
    accent: "from-blue-600 to-indigo-700",
  },
  therapist: {
    title: "康复治疗师",
    subtitle: "Sports Rehab Therapist",
    description: "AI 康复方案确认、康复评估、院内康复治疗记录。",
    accent: "from-emerald-500 to-teal-600",
  },
} as const;
