import type { Patient, TaskItem } from "./types";

export const patients: Patient[] = [
  // 门诊待入院
  {
    id: "p1",
    outpatientId: "MZ-20240412-001",
    name: "张建国",
    age: 68,
    gender: "男",
    phone: "138****2341",
    diagnosis: "右膝骨关节炎",
    surgeryName: "右TKA",
    side: "右",
    director: "王主任",
    scheduledAdmission: "2024-04-22",
    status: "outpatient-pending",
    department: "outpatient",
    urgent: true,
    notes: "熟人推荐，加急安排",
  },
  {
    id: "p2",
    outpatientId: "MZ-20240412-002",
    name: "李秀兰",
    age: 72,
    gender: "女",
    phone: "139****5621",
    diagnosis: "左股骨颈骨折",
    surgeryName: "左THA",
    side: "左",
    director: "秦主任",
    scheduledAdmission: "2024-04-23",
    status: "outpatient-pending",
    department: "outpatient",
  },
  {
    id: "p3",
    outpatientId: "MZ-20240413-003",
    name: "陈志强",
    age: 55,
    gender: "男",
    phone: "137****8812",
    diagnosis: "右肩袖损伤",
    surgeryName: "右肩关节镜",
    side: "右",
    director: "王主任",
    scheduledAdmission: "2024-04-24",
    status: "outpatient-pending",
    department: "outpatient",
  },
  {
    id: "p4",
    outpatientId: "MZ-20240413-004",
    name: "周梅芳",
    age: 65,
    gender: "女",
    phone: "135****2245",
    diagnosis: "双膝退行性关节病",
    surgeryName: "左TKA一期",
    side: "左",
    director: "秦主任",
    scheduledAdmission: "2024-04-25",
    status: "outpatient-pending",
    department: "outpatient",
  },

  // 住院 - 待手术
  {
    id: "p5",
    outpatientId: "MZ-20240408-018",
    name: "刘德海",
    age: 70,
    gender: "男",
    phone: "138****6671",
    diagnosis: "右髋骨关节炎",
    surgeryName: "右THA",
    side: "右",
    director: "王主任",
    responsibleDoctor: "朱医生",
    bedNo: "01",
    admissionDate: "2024-04-20",
    surgeryDate: "2024-04-23",
    status: "admitted",
    department: "inpatient",
    isNew: true,
    preOpAbnormal: true,
    preOpFindings: [
      { label: "血红蛋白", value: "98 g/L", abnormal: true },
      { label: "血压", value: "165/95 mmHg", abnormal: true },
      { label: "心电图", value: "窦性心律", abnormal: false },
      { label: "凝血", value: "正常", abnormal: false },
    ],
  },
  {
    id: "p6",
    outpatientId: "MZ-20240409-022",
    name: "吴翠花",
    age: 67,
    gender: "女",
    phone: "139****1182",
    diagnosis: "左膝感染翻修",
    surgeryName: "左TKA翻修",
    side: "左",
    director: "秦主任",
    responsibleDoctor: "许医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "02",
    admissionDate: "2024-04-19",
    surgeryDate: "2024-04-23",
    status: "admitted",
    department: "inpatient",
    infectious: true,
    isNew: false,
    preOpAbnormal: false,
    preOpFindings: [
      { label: "血红蛋白", value: "112 g/L", abnormal: false },
      { label: "血压", value: "128/82 mmHg", abnormal: false },
      { label: "心电图", value: "窦性心律", abnormal: false },
    ],
  },
  // 今日手术
  {
    id: "p7",
    outpatientId: "MZ-20240405-011",
    name: "孙顺英",
    age: 77,
    gender: "女",
    phone: "137****3398",
    diagnosis: "右膝骨关节炎",
    surgeryName: "右TKA",
    side: "右",
    director: "王主任",
    responsibleDoctor: "朱医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "03",
    admissionDate: "2024-04-18",
    surgeryDate: "2024-04-22",
    status: "in-surgery",
    department: "inpatient",
  },
  // 术后
  {
    id: "p8",
    outpatientId: "MZ-20240402-008",
    name: "杨成轩",
    age: 72,
    gender: "男",
    phone: "138****4421",
    diagnosis: "先天性髋关节发育不良",
    surgeryName: "右THA",
    side: "右",
    director: "王主任",
    responsibleDoctor: "许医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "05",
    admissionDate: "2024-04-15",
    surgeryDate: "2024-04-19",
    status: "post-op",
    department: "inpatient",
    communicationDifficult: true,
  },
  {
    id: "p9",
    outpatientId: "MZ-20240331-002",
    name: "胡国玉",
    age: 66,
    gender: "女",
    phone: "139****7821",
    diagnosis: "膝关节退行性病变",
    surgeryName: "左TKA",
    side: "左",
    director: "秦主任",
    responsibleDoctor: "朱医生",
    responsibleTherapist: "朱年鑫",
    bedNo: "08",
    admissionDate: "2024-04-13",
    surgeryDate: "2024-04-15",
    status: "rehab",
    department: "inpatient",
  },
  // 已出院 / 随访
  {
    id: "p10",
    outpatientId: "MZ-20240315-021",
    name: "何宗兰",
    age: 71,
    gender: "女",
    phone: "138****5512",
    diagnosis: "右膝骨关节炎",
    surgeryName: "右TKA",
    side: "右",
    director: "王主任",
    responsibleTherapist: "朱年鑫",
    admissionDate: "2024-04-15",
    surgeryDate: "2024-04-17",
    dischargeDate: "2024-04-22",
    status: "follow-up",
    department: "inpatient",
    followUpStatus: "done",
    followUpResult: "SLR 1，恢复良好",
  },
  {
    id: "p11",
    outpatientId: "MZ-20240316-024",
    name: "范芳进",
    age: 58,
    gender: "女",
    phone: "139****8814",
    diagnosis: "左膝骨关节炎",
    surgeryName: "左UKA",
    side: "左",
    director: "秦主任",
    responsibleTherapist: "朱年鑫",
    admissionDate: "2024-04-19",
    surgeryDate: "2024-04-21",
    dischargeDate: "2024-04-23",
    status: "follow-up",
    department: "inpatient",
    followUpStatus: "needs-second",
    followUpResult: "屈膝依旧，已宣教，建议去康复科",
  },
  {
    id: "p12",
    outpatientId: "MZ-20240320-031",
    name: "闫宗芝",
    age: 75,
    gender: "男",
    phone: "137****1129",
    diagnosis: "感染性膝关节炎",
    surgeryName: "TKA一期翻修",
    side: "左",
    director: "王主任",
    responsibleTherapist: "朱年鑫",
    admissionDate: "2024-04-22",
    surgeryDate: "2024-04-24",
    dischargeDate: "2024-05-08",
    status: "follow-up",
    department: "inpatient",
    followUpStatus: "pending",
    followUpResult: "卧床",
  },
];

export const todayTasks: Record<string, TaskItem[]> = {
  secretary: [
    { id: "t1", title: "拨打电话确认入院时间", patientName: "张建国", priority: "high", type: "call", due: "今日 10:00" },
    { id: "t2", title: "拨打电话确认入院时间", patientName: "李秀兰", priority: "high", type: "call", due: "今日 11:00" },
    { id: "t3", title: "推送入院前宣教内容", patientName: "陈志强", priority: "medium", type: "education", due: "今日 14:00" },
    { id: "t4", title: "办理入院手续 + 床旁宣教", patientName: "刘德海", bedNo: "01", priority: "medium", type: "admission" },
    { id: "t5", title: "08:00 护理交班记录", priority: "high", type: "handover", due: "今日 08:00" },
    { id: "t6", title: "床旁导管记录单填写", patientName: "杨成轩", bedNo: "05", priority: "medium", type: "nursing" },
  ],
  "doctor-on-duty": [
    { id: "d1", title: "OCR 录入术前检查量表", patientName: "刘德海", bedNo: "01", priority: "high", type: "ocr", due: "今日 16:00" },
    { id: "d2", title: "OCR 录入术前检查量表", patientName: "吴翠花", bedNo: "02", priority: "high", type: "ocr", due: "今日 16:00" },
    { id: "d3", title: "异常指标复核 - 刘德海 Hb 98", priority: "high", type: "review" },
    { id: "d4", title: "推送结果至王主任团队", priority: "medium", type: "push" },
  ],
  "surgical-team": [
    { id: "s1", title: "审核术前结果，决定是否如期手术", patientName: "刘德海", bedNo: "01", priority: "high", type: "decision" },
    { id: "s2", title: "审核术前结果，决定是否如期手术", patientName: "吴翠花", bedNo: "02", priority: "high", type: "decision" },
    { id: "s3", title: "填写术中量表", patientName: "孙顺英", bedNo: "03", priority: "high", type: "intra-op", due: "术后即时" },
    { id: "s4", title: "确认明日手术名单", priority: "medium", type: "schedule" },
  ],
  therapist: [
    { id: "th1", title: "查看术中量表，制定康复方案", patientName: "孙顺英", bedNo: "03", priority: "high", type: "plan" },
    { id: "th2", title: "术后第3日康复评估", patientName: "杨成轩", bedNo: "05", priority: "high", type: "assess" },
    { id: "th3", title: "术后第7日康复出院评估", patientName: "胡国玉", bedNo: "08", priority: "medium", type: "discharge" },
    { id: "th4", title: "电话随访 - 范芳进 (需2次随访)", priority: "high", type: "follow-up" },
    { id: "th5", title: "电话随访 - 闫宗芝 (超时未填写)", priority: "high", type: "follow-up" },
  ],
};

export const roleMeta = {
  secretary: {
    title: "护士 / 科室秘书",
    subtitle: "Nurse & Secretary",
    description: "负责门诊待入院电话沟通、宣教推送、入院办理及住院护理交班。",
    accent: "from-sky-500 to-blue-600",
  },
  "doctor-on-duty": {
    title: "值班医生",
    subtitle: "Doctor on Duty",
    description: "汇总术前检查量表，OCR 录入并推送医疗团队，标记异常指标。",
    accent: "from-cyan-500 to-teal-600",
  },
  "surgical-team": {
    title: "手术医疗团队",
    subtitle: "Surgical Team",
    description: "审核术前结果决定手术与否,填写术中量表，向治疗师交接。",
    accent: "from-blue-600 to-indigo-700",
  },
  therapist: {
    title: "治疗师",
    subtitle: "Therapist",
    description: "制定康复方案、术后随访、康复出院确认与智能随访干预。",
    accent: "from-emerald-500 to-teal-600",
  },
} as const;
